apiVersion: v1
kind: ConfigMap
metadata:
  name: mega-uploader-config
  namespace: mega-uploader
data:
  COGNITO_CLIENT_ID: 5pgshmijcotuq03ur8d3sa73uk
  COGNITO_DOMAIN: https://mega-upload-saas.auth.us-east-1.amazoncognito.com
  COGNITO_REDIRECT_URI: http://localhost/auth/cli/callback
  COGNITO_REGION: us-east-1
  COGNITO_USER_POOL_ID: us-east-1_MuSEs6gb1
  SERVER_ADDR: 0.0.0.0:80
  STS_EXTERNAL_ID: dpaas-cli-auth
  STS_ROLE_ARN: arn:aws:iam::318361291322:role/server-mega-upload-assumable-role
  REDIS_URL: redis://10.90.0.4:6379/0
